disabled_rules: # rule identifiers to exclude from running
  - line_length
  - vertical_parameter_alignment
  - implicit_getter
opt_in_rules: # some rules are only opt-in
  - empty_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - JZCalendarWeekView
  - Carthage
  - pabau2/src/Model
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
